using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using Misan.Modules.Clinical.Domain.Entities;
using System.IO;

namespace Misan.Modules.Clinical.Infrastructure.Services;

public class PrescriptionPdfService
{
    public byte[] GeneratePrescription(Prescription prescription, string hakeemName, string patientName)
    {
        // QuestPDF License
        QuestPDF.Settings.License = LicenseType.Community;

        var document = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(2, Unit.Centimetre);
                page.PageColor(Colors.White);
                page.DefaultTextStyle(x => x.FontSize(12));

                page.Header()
                    .Text($"Al-Nukhwa Clinic - Prescription")
                    .SemiBold().FontSize(20).FontColor(Colors.Green.Medium);

                page.Content()
                    .PaddingVertical(1, Unit.Centimetre)
                    .Column(x =>
                    {
                        x.Item().Text($"Hakeem: {hakeemName}").Bold();
                        x.Item().Text($"Patient: {patientName}").Bold();
                        x.Item().Text($"Date: {prescription.CreatedAt:yyyy-MM-dd}");
                        
                        x.Spacing(20);
                        
                        x.Item().LineHorizontal(1);
                        
                        x.Item().Text("Rx").FontSize(24).Bold().FontColor(Colors.Grey.Darken2);

                        x.Item().Table(table =>
                        {
                            table.ColumnsDefinition(columns =>
                            {
                                columns.RelativeColumn(3);
                                columns.RelativeColumn(1);
                                columns.RelativeColumn(3);
                            });

                            table.Header(header =>
                            {
                                header.Cell().Element(CellStyle).Text("Remedy");
                                header.Cell().Element(CellStyle).Text("Dosage");
                                header.Cell().Element(CellStyle).Text("Instructions");

                                static IContainer CellStyle(IContainer container)
                                {
                                    return container.DefaultTextStyle(x => x.SemiBold()).PaddingVertical(5).BorderBottom(1).BorderColor(Colors.Grey.Lighten2);
                                }
                            });

                            foreach (var item in prescription.Items)
                            {
                                table.Cell().Element(CellStyle).Text(item.Remedy);
                                table.Cell().Element(CellStyle).Text(item.Dosage);
                                table.Cell().Element(CellStyle).Text(item.Instructions);

                                static IContainer CellStyle(IContainer container)
                                {
                                    return container.PaddingVertical(5).BorderBottom(1).BorderColor(Colors.Grey.Lighten3);
                                }
                            }
                        });
                    });

                page.Footer()
                    .AlignCenter()
                    .Text(x =>
                    {
                        x.Span("Generated by Al-Nukhwa Platform");
                        x.CurrentPageNumber();
                    });
            });
        });

        return document.GeneratePdf();
    }
}
