// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Misan.Modules.Practitioner.Infrastructure.Database;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Misan.Modules.Practitioner.Migrations
{
    [DbContext(typeof(PractitionerDbContext))]
    partial class PractitionerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("practitioner")
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Misan.Modules.Practitioner.Domain.Entities.Clinic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("HakeemId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<double>("MapLat")
                        .HasColumnType("double precision");

                    b.Property<double>("MapLng")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HakeemId");

                    b.ToTable("Clinics", "practitioner");
                });

            modelBuilder.Entity("Misan.Modules.Practitioner.Domain.Entities.ClinicFee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.ToTable("ClinicFees", "practitioner");
                });

            modelBuilder.Entity("Misan.Modules.Practitioner.Domain.Entities.ClinicSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("AfternoonEnd")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("AfternoonStart")
                        .HasColumnType("interval");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("uuid");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean");

                    b.Property<TimeSpan>("MorningEnd")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("MorningStart")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.ToTable("ClinicSchedules", "practitioner");
                });

            modelBuilder.Entity("Misan.Modules.Practitioner.Domain.Entities.ClinicService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("uuid");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.ToTable("ClinicServices", "practitioner");
                });

            modelBuilder.Entity("Misan.Modules.Practitioner.Domain.Entities.Hakeem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CnicNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Rating")
                        .HasColumnType("numeric");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Hakeems", "practitioner");
                });

            modelBuilder.Entity("Misan.Modules.Practitioner.Domain.Entities.HakeemDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("HakeemId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Verified")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("HakeemId");

                    b.ToTable("HakeemDocuments", "practitioner");
                });

            modelBuilder.Entity("Misan.Modules.Practitioner.Domain.Entities.HakeemLanguage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("HakeemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HakeemId");

                    b.ToTable("HakeemLanguages", "practitioner");
                });

            modelBuilder.Entity("Misan.Modules.Practitioner.Domain.Entities.HakeemQualification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("HakeemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HakeemId");

                    b.ToTable("HakeemQualifications", "practitioner");
                });

            modelBuilder.Entity("Misan.Modules.Practitioner.Domain.Entities.HakeemSpecialization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("HakeemId")
                        .HasColumnType("uuid");

                    b.Property<string>("SpecializationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HakeemId");

                    b.ToTable("HakeemSpecializations", "practitioner");
                });

            modelBuilder.Entity("Misan.Modules.Practitioner.Domain.Entities.ScheduleBreak", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval");

                    b.Property<Guid>("HakeemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ScheduleBreaks", "practitioner");
                });

            modelBuilder.Entity("Misan.Modules.Practitioner.Domain.Entities.ScheduleConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AutoAccept")
                        .HasColumnType("boolean");

                    b.Property<int>("BufferTimeMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid>("HakeemId")
                        .HasColumnType("uuid");

                    b.Property<int>("NoticePeriodHours")
                        .HasColumnType("integer");

                    b.Property<int>("SlotDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HakeemId")
                        .IsUnique();

                    b.ToTable("ScheduleConfigs", "practitioner");
                });

            modelBuilder.Entity("Misan.Modules.Practitioner.Domain.Entities.ClinicFee", b =>
                {
                    b.HasOne("Misan.Modules.Practitioner.Domain.Entities.Clinic", null)
                        .WithMany("Fees")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Misan.Modules.Practitioner.Domain.Entities.ClinicSchedule", b =>
                {
                    b.HasOne("Misan.Modules.Practitioner.Domain.Entities.Clinic", null)
                        .WithMany("Schedules")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Misan.Modules.Practitioner.Domain.Entities.ClinicService", b =>
                {
                    b.HasOne("Misan.Modules.Practitioner.Domain.Entities.Clinic", null)
                        .WithMany("Services")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Misan.Modules.Practitioner.Domain.Entities.HakeemDocument", b =>
                {
                    b.HasOne("Misan.Modules.Practitioner.Domain.Entities.Hakeem", null)
                        .WithMany("Documents")
                        .HasForeignKey("HakeemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Misan.Modules.Practitioner.Domain.Entities.HakeemLanguage", b =>
                {
                    b.HasOne("Misan.Modules.Practitioner.Domain.Entities.Hakeem", null)
                        .WithMany("Languages")
                        .HasForeignKey("HakeemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Misan.Modules.Practitioner.Domain.Entities.HakeemQualification", b =>
                {
                    b.HasOne("Misan.Modules.Practitioner.Domain.Entities.Hakeem", null)
                        .WithMany("Qualifications")
                        .HasForeignKey("HakeemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Misan.Modules.Practitioner.Domain.Entities.HakeemSpecialization", b =>
                {
                    b.HasOne("Misan.Modules.Practitioner.Domain.Entities.Hakeem", null)
                        .WithMany("Specializations")
                        .HasForeignKey("HakeemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Misan.Modules.Practitioner.Domain.Entities.Clinic", b =>
                {
                    b.Navigation("Fees");

                    b.Navigation("Schedules");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("Misan.Modules.Practitioner.Domain.Entities.Hakeem", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Languages");

                    b.Navigation("Qualifications");

                    b.Navigation("Specializations");
                });
#pragma warning restore 612, 618
        }
    }
}
